name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: cicdprojectregistry.azurecr.io
  IMAGE_NAME: flask-app
  WEBAPP_NAME: cicdproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
